Importing Required Libraries

In [1]:
import numpy as np
import pandas as pd

Importing Dataset 

In [4]:
data1 = pd.read_csv('spam.csv', encoding = 'latin-1') # Kaggle dataset
data1 = data1.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis = 1)
print("Kaggle dataset head:")
data1.head()

Kaggle dataset head:


label                                                msg
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
data2 = pd.ExcelFile('revisedindiandataset.xls')
data2 = data2.parse(0)
data2 = data2.drop(['code'], axis = 1)
print("Our dataset head:")
data2.head()

Our dataset head:


label                                                msg
0   ham  Dear Customer, +916300623587 is now available ...
1   ham  Dear Customer, You have a missed call from +91...
2  spam  Join Hike to get Rs 40. Earn upto Rs. 10,000 b...
3  spam  Just sent you some money and invited you to Hi...
4  spam  Just sent you some money and invited you to Hi...

In [8]:
data = pd.concat([data1, data2])

# Data Preprocessing

Encoding label

In [9]:
# encoding Data
data['label'] = pd.factorize(data['label'])[0]
data.head()

label                                                msg
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [11]:
# module for removing unwanted words
import re
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords

# for stemming words
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\manoh\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [13]:
temp = []
for row in data.itertuples():
    rev = row[2]
    rev = rev.lower() # lower casing every word
    rev = rev.split()
    ps = PorterStemmer()
    # stemming and removing stopwords
    rev = [ps.stem(word) for word in rev if not word in set(stopwords.words("english"))] 
    rev = " ".join(rev)
    temp.append(rev)

In [14]:
data['msg'] = temp

Splitting Data for train and test

In [15]:
# splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data['msg'], data['label'], test_size = 0.25, random_state = 0)

# Extracting features using Bag of words

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 410)
cv.fit(data['msg'])
X_train = cv.transform(X_train)
X_test = cv.transform(X_test)

# Using diffrent machine learning algorithms

# SVM

In [19]:
# Training classifier
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [20]:
#Confusion Matrix                                               
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2025   31]
 [  74  405]]


# Naive Bayes

In [17]:
# Training classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [18]:
#Confusion Matrix                                               
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1920  136]
 [  67  412]]


# Logistic Regression

In [21]:
# Training classifier
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [22]:
#Confusion Matrix                                               
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2021   35]
 [  80  399]]


# K-Nearest Neighbours

In [23]:
# Training classifier
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3 , p = 2)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [24]:
#Confusion Matrix                                               
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2041   15]
 [ 131  348]]


# Decision Tree

In [26]:
# Training classifier
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [27]:
#Confusion Matrix                                               
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2001   55]
 [  70  409]]


# Random Forest

In [28]:
# Training classifier
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=20, criterion='entropy')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [29]:
#Confusion Matrix                                               
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2029   27]
 [  68  411]]
